GVM2-18 #comment Refactor script/listall.

diff --git a/scripts/listall b/scripts/listall
--- a/scripts/listall
+++ b/scripts/listall
@@ -7,10 +7,13 @@
 dep_load() {
     local base="$(builtin cd "$(dirname "${BASH_SOURCE[0]}")" && /bin/pwd)"
     local deps; deps=(
-        "function/_bash_pseudo_hash.sh"
-        "function/display_notices.sh"
-        "function/detect_runos.sh"
-        "function/find_available.sh"
+        "../scripts/function/_bash_pseudo_hash.sh"
+        "../scripts/function/_shell_compat.sh"
+        "../scripts/function/detect_runos.sh"
+        "../scripts/function/display_notices.sh"
+        "../scripts/function/locale_text.sh"
+        "../scripts/function/detect_runos.sh"
+        "../scripts/function/find_available.sh"
     )
     for file in "${deps[@]}"
     do
@@ -18,64 +21,36 @@ dep_load() {
     done
 }; dep_load; unset -f dep_load
 
-show_usage() {
-cat << EOF
-usage: gvm listall [options]
-
-OPTIONS:
-    -a, --all                   List all versions available
-    -B, --binary                List available pre-built versions available
-    -s, --source                List available source versions available
-        --porcelain             Machine-readable output
-    -h, --help                  Show this message
-
-Command line arguments
-----------------------
-Without any arguments source (-s|--source) is selected by default. Only bonafide
-releases are listed: legacy "weekly" and "release" tags are omitted. The source
-list is filtered to only include versions that can be built on the running
-platform. The binary list is filtered to only include versions that should have
-a binary package available for the running platform.
-
-EOF
-}
-
-read_command_line() {
-    for option in "$@"; do
-        case "${option}" in
-            -a|--all)
-                opt_filter="all"
-            ;;
-            -B|--binary)
-                opt_filter="binary"
-            ;;
-            -s|--source)
-                opt_filter="source"
-            ;;
-            --porcelain)
-                opt_porcelein=true
-            ;;
-            -h|--help)
-                show_usage; exit 0
-            ;;
-            *)
-                __gvm_display_warning "Unrecognized command line argument: '$option'"
-                show_usage
-                exit 65 # Bad arguments
-            ;;
-        esac
-    done
-}
-
 list_all() {
+    local os="${1}"; shift
     local source_url="${1}"; shift
-    local scope="${1:-source}" # all, binary, source
+    local opt_scope="${1:-source}"; shift # all, binary, source
+    local opt_porcelain="${1}"; shift
+    local opt_quiet="${1}"
     local filter='^(go([0-9]+(\.[0-9]+[a-z0-9]*)*))$' # all versions
     local filtered_list; filtered_list=()
 
-    [[ -z "${source_url// /}" ]] || (echo "" && return 1)
+    [[ -z "${os// /}" ]] && RETVAL="" && echo "${RETVAL}" && return 1
 
-    if [[ "${scope}" == "binary" ]]
+    # validate source_url exists
+    if [[ -z "${source_url// /}" ]]
+    then
+        __gvm_locale_text_for_key "specify_listall_source_url" > /dev/null
+        __gvm_display_fatal "${RETVAL}"
+    fi
+
+    # validate scope
+    case "${opt_scope}" in
+        all | binary | source )
+            ;;
+        *)
+            __gvm_locale_text_for_key "listall_scope_invalid" > /dev/null
+            __gvm_display_fatal "${RETVAL}"
+            ;;
+    esac
+
+    # update filters if scope is set to "binary", default is "source"
+    if [[ "${opt_scope}" == "binary" ]]
     then
         # go1 (go1.2.2, go1.3+)
         #
@@ -93,8 +68,7 @@ list_all() {
     #
     # macOS fixups
     #
-    local runos="$(__gvm_detect_runos)"
-    if [[ "${runos%%,*}" == "darwin" ]]
+    if [[ "${os}" == "darwin" ]]
     then
         # Changes to macOS compilers as of macOS 10.12 (Sierra) prevent builds of:
         #
@@ -103,7 +77,7 @@ list_all() {
         #
         # Binaries are still available for the affected versions.
         #
-        if [[ "${opt_filter}" == "source" ]]
+        if [[ "${opt_scope}" == "source" ]]
         then
             # go1 (go1.4, go1.7.1+)
             #
@@ -120,85 +94,147 @@ list_all() {
             filter="${filter_v1}|${filter_v2}|${filter_v3}|${filter_v4}"
         fi
     fi
-    unset runos
+
+    #
+    # Finally, do it
+    #
+    if [[ "${GVM_DEBUG}" -eq 1 ]]
+    then
+        printf "%s:\n" "${BASH_SOURCE[0]##*/}::list_all() running with"
+        echo "  GOROOT         -> ${GOROOT}"
+        echo "  GOOS           -> ${os}"
+        echo "  _scope         -> ${opt_scope}"
+        echo "  _source_url    -> ${source_url}"
+    fi
+
+    if [[ "${opt_porcelain}" == false && "${opt_quiet}" == false ]]
+    then
+        __gvm_locale_text_for_key "title/gvm_go_listall" > /dev/null
+        printf "\n%s\n\n" "${RETVAL}"
+    fi
 
     local available_hash; available_hash=( "$(__gvm_find_available "${source_url}")" )
 
     if [[ ${#available_hash[@]} -eq 0 ]]
     then
-        unset available_hash
-        echo "" && return 1
+        __gvm_locale_text_for_key "title/listall_failed" > /dev/null
+        __gvm_display_fatal "${RETVAL}"
+        return 1
     fi
 
-    local available_hash_keys; available_hash_keys=( "$(keysForFakeAssocArray "${available_hash[*]}")" )
+    local available_hash_keys; available_hash_keys=( $(keysForFakeAssocArray "${available_hash[*]}") )
     local _version
-    for _version in $available_hash_keys
+    for _version in "${available_hash_keys[@]}"
     do
         [[ "${_version}" =~ ${filter} ]] && filtered_list+=( "${_version}" )
     done
     unset _version
     unset available_hash_keys
 
-    printf "%s" "${filtered_list[*]}"
+    local _version
+    for _version in "${filtered_list[@]}"
+    do
+        if [[ "${opt_porcelain}" == false ]]
+        then
+            printf "   %s\n" "${_version}"
+        else
+            printf "%s\n" "${_version/ }"
+        fi
+    done
+    unset _version
 
-    unset filtered_list
-    unset available_hash
-    unset filter
-    unset scope
-    unset source_url
+    if [[ "${opt_porcelain}" == false ]]
+    then
+        echo
+    fi
+
     return 0
 }
 
-main() {
-    # setup script global vars
-    local opt_filter="source"
-    local opt_porcelein=false
+_exit()
+{
+  stty sane; echo; __gvm_display_fatal "caught signal, shutting down"
 
-    trap '__gvm_display_fatal "Canceled!"' INT
-    read_command_line "$@"
+  # @TODO: additional cleanup?
 
-    if [[ "${opt_porcelein}" == false ]]
+  wait; stty sane; exit 1
+}
+
+trap '_exit' SIGINT SIGQUIT SIGTERM
+
+main()
+{
+    local opt_scope="source"
+    local opt_porcelain=false
+    local opt_quiet=false
+    local args; args=()
+    local rslt
+
+    if [[ -n "$GVM_DEBUG" ]] && [[ -n "$GVM_DEBUG_LEVEL" && "$GVM_DEBUG_LEVEL" -gt 1 ]]
     then
-        echo
-        __gvm_display_message "gvm gos (available)"
-        echo
+        set -x
     fi
 
-    local repo_source="https://go.googlesource.com/go"
-    local version_list=( "$(list_all "${repo_source}" "${opt_filter}")" )
+    local _run_os
+    local os os_version os_arch
+    __gvm_detect_runos > /dev/null
+    _run_os="${RETVAL}"
+    os="${_run_os%%,*}"
+    os_version="${_run_os#*,}"; os_version="${os_version%,*}"
+    os_arch="${_run_os##*,}"
+    unset _run_os
 
-    if [[ $? -ne 0 ]]
+    local source_url="https://go.googlesource.com/go"
+
+    while true
+    do
+        case "${1}" in
+            -a | --all)
+                opt_scope="all"
+                ;;
+            -B | --binary)
+                opt_scope="binary"
+                ;;
+            -s | --source)
+                opt_scope="source"
+                ;;
+            --porcelain )
+                opt_porcelain=true
+                ;;
+            -q | --quiet )
+                opt_quiet=true
+                ;;
+            -h | ? | help | --help )
+                __gvm_locale_text_for_key "help/usage_listall" > /dev/null
+                printf "%s\n" "${RETVAL}"
+                return 0
+                ;;
+            *)
+                if [[ "${1:0:1}" == '-' ]]
+                then
+                    __gvm_locale_text_for_key "unrecognized_command" > /dev/null
+                    printf "%s: %s\n\n" "${RETVAL}" "${1:-empty}"
+                    __gvm_locale_text_for_key "help/usage_listall" > /dev/null
+                    printf "%s\n" "${RETVAL}"
+                    return 1
+                fi
+                # only save arg if it contains more than spaces
+                [[ -n "${1// /}" ]] && args+=( "${1}" )
+                ;;
+        esac
+        # guard against accidents...
+        shift; [[ "$#" -eq 0 ]] && break
+    done
+
+    list_all "${os}" "${source_url}" "${opt_scope}" "${opt_porcelain}" "${opt_quiet}"; rslt=$?
+
+    if [[ -n "$GVM_DEBUG" ]] && [[ -n "$GVM_DEBUG_LEVEL" && "$GVM_DEBUG_LEVEL" -gt 1 ]]
     then
-        __gvm_display_fatal "Failed to retrieve list of available versions"
-        return 1
+        set +x
     fi
 
-    local _version
-    if [[ "${opt_porcelein}" == false ]]
-    then
-        for _version in $version_list
-        do
-            echo "   ${_version}"
-        done
-    else
-        for _version in $version_list
-        do
-            echo "${_version}"
-        done
-    fi
-    unset _version
-    unset available_hash_keys
-
-    if [[ "${opt_porcelein}" == false ]]
-    then
-        echo
-    fi
-
-    unset version_list
-    unset repo_source
-    unset available_hash
-
-    return 0
+    return "${rslt}"
 }
 
 main "$@"
+
